services:

    fiftydeg.sylius_scripts_plugin.menu.admin_menu_listener:
        class: FiftyDeg\SyliusScriptsPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addShopSettingsMenu }
